env:
  global:
    - LANG:tr_TR.UTF-8

language: php

php:
    - 7.0

before_script:
    - phpenv rehash
    - composer install

script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit -c phpunit.xml.dist

after_success:
    - php vendor/bin/coveralls -v