env:
  global:
    - LANG:tr_TR.UTF-8

language: php

php:
    - 7.0

before_script:
    - phpenv rehash
    - composer install

script: 
	- phpunit ExchangeProviderTest.php
	- php vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  - travis_retry php vendor/bin/coveralls
  # or enable logging
  - travis_retry php vendor/bin/coveralls -v